export const SEQUENCE = {
  ARROW_UP: '\u001B[A',
  ARROW_DOWN: '\u001B[B',
  ARROW_RIGHT: '\u001B[C',
  ARROW_LEFT: '\u001B[D',
  SPACE: ' ',
  ENTER: '\r',
  CONTROL_C: '\u0003',
  CURSOR_SHOW: '\x1B[?25h',
  CURSOR_HIDE: '\x1B[?25l',
  LINE_UP: '\x1b[1A',
  LINE_LEFT: '\x1b[1C',
  LINE_START: '\x1b[1G',
  LINE_CLEAR: '\x1b[2K',
} as const;
